name: Check

on:
  push:
    paths: ['*.ts']
  pull_request:
    paths: ['*.ts']

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - uses: pnpm/action-setup@v2
        with:
          run_install: false

      - run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
        shell: bash
        id: pnpm-config

      - run: echo "YEAR_MONTH=$(/bin/date -u "+%Y%m")" >> $GITHUB_OUTPUT
        shell: bash
        id: cache-rotation

      - uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-config.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-cache-${{ steps.cache-rotation.outputs.YEAR_MONTH }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-cache-${{ steps.cache-rotation.outputs.YEAR_MONTH }}-

      - run: pnpm install --frozen-lockfile --prefer-offline --silent
        shell: bash
        env:
          HUSKY: 0

      - run: pnpm type-check

      - run: pnpm lint

      - run: pnpm test
