name: Release

on:
  release:
    types: [published]

jobs:
  check:
    uses: ./.github/workflows/check.yml
    secrets: inherit

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [check]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/base

      - run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
